name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: |
          # Cập nhật pip và cài đặt các công cụ cần thiết để build
          python -m pip install --upgrade pip
          python -m pip install build cx_Freeze

      - name: Build release distributions
        run: |
          # Tạo bản phân phối để phát hành
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      # Quan trọng: Quyền này cần thiết để hỗ trợ "Trusted Publishing"
      id-token: write

    environment:
      name: pypi
      # Bạn có thể chỉ định URL dự án trên PyPI tại đây (tùy chọn)
      # url: https://pypi.org/project/YOURPROJECT

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
